### ISSUE TITLE
CLI based IPMI query

### ISSUE THREAD

**Issue by vj396** [michaeljs1990/collins-go-cli#9]
we can query for the asset, based on the IP address, but sometimes we would also need to query for the IPMI IP, say something like `collins find --ipmi_ip <ipmi ip>`?

**Comment by michaeljs1990** [comment]
Currently the following will get you similar results. I additionally landed support in https://github.com/michaeljs1990/collins-go-cli/commit/c9cd0a7f10b2b3d7b00deaa7234431c471c901e6 so that the output is now rendered properly.
```
eatingthenight@gentoo ~/code/collins-go-cli $ ./collins-go-cli query -a ipmi_address:10.0.0.178
M0000001        plex-8316f3de71.pit1.terame.com plexnode        Allocated       PRODUCTION      PLEX            10.0.0.178
```
I'm not sure if adding a flag for everything is the right way forward or not but right now I am messing around with better man page support so figuring out all the attributes you have available from the command line is easier/more transparent.

I'll cut a release with the ipmi_address output fix in it soon.

**Comment by michaeljs1990** [comment]
I think support for this is ok as it currently stands (or can be addressed with docs) but if not feel free to re-open.
